### ISSUE TITLE
Error running jumppad check or jumppad up

### ISSUE THREAD

**Issue by Tonysysop** [jumppad-labs/terraform-workshop#5]
ERRO Error checking server version error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x102ac8578]

goroutine 1 [running]:
github.com/jumppad-labs/jumppad/pkg/clients/container.NewDockerTasks({0x105272ad8, 0x14000364880}, {0x0?, 0x0}, 0x0, {0x0?, 0x0})
	/home/runner/work/jumppad/jumppad/pkg/clients/container/docker_tasks.go:69 +0x158
github.com/jumppad-labs/jumppad/pkg/clients/system.(*SystemImpl).checkDocker(0x14000d1fc68)
	/home/runner/work/jumppad/jumppad/pkg/clients/system/system.go:199 +0x40
github.com/jumppad-labs/jumppad/pkg/clients/system.(*SystemImpl).Preflight(0x0?)
	/home/runner/work/jumppad/jumppad/pkg/clients/system/system.go:86 +0x24
github.com/jumppad-labs/jumppad/cmd.glob..func1(0x1066ae7a0?, {0x106721008?, 0x0?, 0x0?})
	/home/runner/work/jumppad/jumppad/cmd/check.go:18 +0x28
github.com/spf13/cobra.(*Command).execute(0x1066ae7a0, {0x106721008, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x1066af8e0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/jumppad-labs/jumppad/cmd.Execute({0x104b836bc?, 0x0?}, {0x104b845a0?, 0x1026dac7c?}, {0x104b841b0?, 0x140000021a0?})
	/home/runner/work/jumppad/jumppad/cmd/root.go:135 +0xf4
main.main()
	/home/runner/work/jumppad/jumppad/main.go:14 +0x4c

~/desktop/terraform-workshop/terraform-workshop main
❯

**Comment by nicholasjackson** [comment]
Hey @Tonysysop, the error is a bug in `jumppad` that has been fixed in the latest version, the crash is actually caused because Jumppad can not contact the docker engine. Did you have docker or podman running when you ran jumppad up?

**Comment by Tonysysop** [comment]
> Hey @Tonysysop, the error is a bug in `jumppad` that has been fixed in the latest version, the crash is actually caused because Jumppad can not contact the docker engine. Did you have docker or podman running when you ran jumppad up?

yes i had my docker daemon running
